name: 'deploy'
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

permissions:
  contents: write
  pull-requests: read
  actions: write

env:
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
  SUPERFICIALDEPOSITS_KEY: ${{ secrets.SUPERFICIALDEPOSITS_KEY }}
  SUPERFICIALDEPOSITS_IP: ${{ secrets.SUPERFICIALDEPOSITS_IP }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: 'build and push'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Prepare SSH'
        run: mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan -t rsa -H ${{ env.SUPERFICIALDEPOSITS_IP }} >> ~/.ssh/known_hosts

      - name: 'Prepare key'
        run: eval $(ssh-agent) && echo "${{ env.SUPERFICIALDEPOSITS_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-add ~/.ssh/id_rsa

      - name: 'Download superficial deposits data'
        run: scp ubuntu@${{ env.SUPERFICIALDEPOSITS_IP }}:~/superficialdeposits_shape.zip data/Losmasse

      - name: 'Download fjord data'
        run: scp ubuntu@${{ env.SUPERFICIALDEPOSITS_IP }}:~/fjordkatalogen_omrade.zip data/Fjord

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: erikbjo
          password: ${{ env.DOCKER_PAT }}

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'ls la'
        run: ls -la data/Losmasse

      - name: 'Set permissions'
        run: chmod 644 data/Losmasse/superficialdeposits_shape.zip

      - name: 'Build and push'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/erikbjo/server:latest
          context: .
